<?php

/**
 * @file
 * Weather Widget module file.
 */

/**
 * Implements hook_theme().
 */
function weather_widget_theme($existing, $type, $theme, $path) {
  return [
    'weather_widget' => [
      'template' => 'block--weather-widget',
      'variables' => [
        'temp' => null,
        'city' => null,
        'image' => null,
      ],
    ],
  ];
}

/**
 * Implements hook_preprocess_block.
 */
function weather_preprocess_block__weather_widget(&$variables) {
  $variables['#cache']['contexts'][] = 'url';
}
